@BuberDinner_Api_Auth = https://localhost:7295/Authentication

POST {{BuberDinner_Api_Auth}}/Register
Accept: application/json
Content-Type: application/json

{
    "firstName": "FirstName",
    "lastName": "LastName",
    "email": "test@test.com",
    "password": "testpass"
}

###

POST {{BuberDinner_Api_Auth}}/Login
Accept: application/json
Content-Type: application/json

{
    "email": "test@test.com",
    "password": "testpass"
}

###

