@BuberDinner.Host = https://localhost:7295/hosts

@hostId = 8B16A20F-B0E9-4010-BA92-1A1EDD139AD6

@token = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJlOTY3OTBkZC1kYmIzLTRkYWMtYjExNS1iZTM1NWU3OTgxYTciLCJnaXZlbl9uYW1lIjoiRmlyc3ROYW1lIiwiZmFtaWx5X25hbWUiOiJMYXN0TmFtZSIsImp0aSI6IjAyYzg5MGRkLTY2NmYtNDdmNi1hZGU1LTJjNGUwMzY4MjJhYyIsImV4cCI6MTcxNTUyODYyMCwiaXNzIjoiQnViZXJEaW5uZXIiLCJhdWQiOiJCdWJlckRpbm5lciJ9.FBDPRzjioTFXWSm4hQvuH8BflcbgAii1M3UOnyetij4

POST {{BuberDinner.Host}}/{{hostId}}/menus
Accept: application/json
Content-Type: application/json
Authorization: Bearer {{token}}

{
  "name": "Menu 2",
  "description": "Menu 2 description",
  "sections": [
  {
	  "name": "Section 1",
	  "description": "Section 1 description",
	  "items": [
		{
		  "name": "Item 1",
		  "description": "Item 1 description"
		},
		{
		  "name": "Item 2",
		  "description": "Item 2 description"
		}
	  ]
	}]
}
###
