@BuberDinner.Host = https://localhost:7295/hosts

@hostId = 8B16A20F-B0E9-4010-BA92-1A1EDD139AD5

@token = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJjNGI2YzBhOC1kNDFmLTQ4ZjItYmZiOC1jZjYyZDBjNzg0ODIiLCJnaXZlbl9uYW1lIjoiRmlyc3ROYW1lIiwiZmFtaWx5X25hbWUiOiJMYXN0TmFtZSIsImp0aSI6IjYzODQ1NzNlLWI2ODktNGI0Yy05ZjIxLWJiNzc5YTlkYTA1ZSIsImV4cCI6MTcxMzY5Nzk3OSwiaXNzIjoiQnViZXJEaW5uZXIiLCJhdWQiOiJCdWJlckRpbm5lciJ9.5JUxD1IjMDb3UoGTxL2ZZIxrhuoZ09ZOo_Xx2VwtgXc

POST {{BuberDinner.Host}}/{{hostId}}/menus
Accept: application/json
Content-Type: application/json
Authorization: Bearer {{token}}

{
  "name": "Menu 1",
  "description": "Menu 1 description",
  "sections": [
  {
	  "name": "Section 1",
	  "description": "Section 1 description",
	  "items": [
		{
		  "name": "Item 1",
		  "description": "Item 1 description"
		},
		{
		  "name": "Item 2",
		  "description": "Item 2 description"
		}
	  ]
	}]
}
###
