@BuberDinner.Host = https://localhost:7295/hosts

@hostId = 8B16A20F-B0E9-4010-BA92-1A1EDD139AD6

@token = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJhZjAxZDg5ZC1kYTZjLTQyYmMtYjM0Yi1iMzAwMzhjNGI2N2QiLCJnaXZlbl9uYW1lIjoiRmlyc3ROYW1lIiwiZmFtaWx5X25hbWUiOiJMYXN0TmFtZSIsImp0aSI6ImRhNWYyYjQ5LTBkYTUtNDFiOC05NzI2LTRlMmY2MjFmMWVlOCIsImV4cCI6MTcxNTUzMzM5NCwiaXNzIjoiQnViZXJEaW5uZXIiLCJhdWQiOiJCdWJlckRpbm5lciJ9.LQRb1kCGonL2INBBNAhWlHsi5A9AfRE-xDDnT-u_sYU

POST {{BuberDinner.Host}}/{{hostId}}/menus
Accept: application/json
Content-Type: application/json
Authorization: Bearer {{token}}

{
  "name": "Menu 2",
  "description": "Menu 2 description",
  "sections": [
  {
	  "name": "Section 1",
	  "description": "Section 1 description",
	  "items": [
		{
		  "name": "Item 1",
		  "description": "Item 1 description"
		},
		{
		  "name": "Item 2",
		  "description": "Item 2 description"
		}
	  ]
	}]
}
###
